/**
 * Default social card, generated by src/app/opengraph-image.tsx.
 *
 * A page that declares its own `openGraph` object replaces the parent's, and
 * that includes the images the file convention would have provided — so every
 * page with custom metadata has to point at this explicitly, or it ships with
 * no social image at all.
 */
export const DEFAULT_OG_IMAGE = { url: "/opengraph-image", width: 1200, height: 630 } as const;
