"use client";

import { useState } from "react";
import { Send } from "lucide-react";

const projectTypes = ["Automação","Sistema","API","Integração","Dashboard","Dados","Inteligência Artificial","Consultoria","Outro"];

export function Contact(){
  const [status,setStatus]=useState<"idle"|"loading"|"success"|"error">("idle");
  async function onSubmit(e: React.FormEvent<HTMLFormElement>){e.preventDefault();setStatus("loading");const fd=new FormData(e.currentTarget);const payload=Object.fromEntries(fd.entries());try{const r=await fetch("/api/contact",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});if(!r.ok)throw new Error();setStatus("success");e.currentTarget.reset();}catch{setStatus("error");}}
  return <section id="contato" className="section-space bg-white/[.018]"><div className="container-shell grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="section-kicker">Contato</p><h2 className="section-title">Conte um pouco sobre o processo que você quer melhorar.</h2><p className="section-copy">Quanto mais contexto você enviar, melhor será o diagnóstico inicial. Não precisa definir a tecnologia: descreva o problema, a rotina atual e o resultado esperado.</p></div><form onSubmit={onSubmit} className="card grid gap-4 rounded-3xl p-5 sm:grid-cols-2 sm:p-7"><input aria-label="Nome" name="name" required placeholder="Nome" className="focus-ring rounded-xl border border-white/10 bg-black/15 px-4 py-3.5 outline-none"/><input aria-label="Empresa" name="company" placeholder="Empresa" className="focus-ring rounded-xl border border-white/10 bg-black/15 px-4 py-3.5 outline-none"/><input aria-label="Email" type="email" name="email" required placeholder="Email" className="focus-ring rounded-xl border border-white/10 bg-black/15 px-4 py-3.5 outline-none"/><input aria-label="WhatsApp" name="whatsapp" placeholder="WhatsApp" className="focus-ring rounded-xl border border-white/10 bg-black/15 px-4 py-3.5 outline-none"/><select aria-label="Tipo de projeto" name="projectType" required defaultValue="" className="focus-ring rounded-xl border border-white/10 bg-[#0a101d] px-4 py-3.5 outline-none"><option value="" disabled>Tipo de projeto</option>{projectTypes.map(x=><option key={x}>{x}</option>)}</select><input name="website" tabIndex={-1} autoComplete="off" className="hidden" aria-hidden="true"/><textarea aria-label="Necessidade" name="message" required minLength={20} rows={6} placeholder="Conte um pouco sobre sua necessidade" className="focus-ring rounded-xl border border-white/10 bg-black/15 px-4 py-3.5 outline-none sm:col-span-2"/><button disabled={status==="loading"} className="focus-ring inline-flex items-center justify-center gap-2 rounded-xl bg-blue-600 px-5 py-3.5 font-bold hover:bg-blue-500 disabled:opacity-60 sm:col-span-2">{status==="loading"?"Enviando...":"Enviar solicitação"}<Send size={17}/></button>{status==="success"?<p className="text-sm text-emerald-300 sm:col-span-2">Solicitação enviada com sucesso.</p>:null}{status==="error"?<p className="text-sm text-red-300 sm:col-span-2">Não foi possível enviar agora. Tente novamente ou use o WhatsApp.</p>:null}</form></div></section>}
